project:
  type: website
  output-dir: docs

website:
  title: "Bryan P. Galligan, S.J."
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Scholarship
      - href: opinion.qmd
        text: Opinion
      - href: media.qmd
        text: Media

format:
  html:
    theme: flatly
    css: styles.css
    toc: FALSE



